// Auto-generated by deploy.mjs — update CONTRACT_ID after deployment
// Run: node scripts/deploy.mjs

export const CONTRACT_CONFIG = {
  contractId: process.env.NEXT_PUBLIC_CONTRACT_ID || "CONTRACT_ADDRESS_HERE",
  network: (process.env.NEXT_PUBLIC_NETWORK || "testnet") as "testnet" | "mainnet",
  rpcUrl:
    process.env.NEXT_PUBLIC_RPC_URL ||
    "https://soroban-testnet.stellar.org",
  networkPassphrase:
    process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE ||
    "Test SDF Network ; September 2015",
  explorerBase:
    process.env.NEXT_PUBLIC_EXPLORER_BASE ||
    "https://stellar.expert/explorer/testnet",
  horizonUrl:
    process.env.NEXT_PUBLIC_HORIZON_URL ||
    "https://horizon-testnet.stellar.org",
} as const;

export type Network = "testnet" | "mainnet";

export const NETWORKS: Record<Network, typeof CONTRACT_CONFIG> = {
  testnet: {
    contractId: CONTRACT_CONFIG.contractId,
    network: "testnet",
    rpcUrl: "https://soroban-testnet.stellar.org",
    networkPassphrase: "Test SDF Network ; September 2015",
    explorerBase: "https://stellar.expert/explorer/testnet",
    horizonUrl: "https://horizon-testnet.stellar.org",
  },
  mainnet: {
    contractId: "",
    network: "mainnet",
    rpcUrl: "https://mainnet.sorobanrpc.com",
    networkPassphrase: "Public Global Stellar Network ; September 2015",
    explorerBase: "https://stellar.expert/explorer/public",
    horizonUrl: "https://horizon.stellar.org",
  },
};
